name: tests

on:
  push:
  pull_request: null

jobs:
  tests:
    name: tests
    strategy:
      matrix:
        pyver: [3.7, 3.8, 3.9]

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Install code
        run: pip install -e .

      - name: lint
        run: |
          pip install flake8
          flake8 esutil

      - name: test
        run: |
          pip install pytest
          pytest -vv esutil
